on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.PRIVATE_KEY}}
          repositories: >-
            ["${{github.event.repository.name}}"]
      - uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9 # v1.6.1
        with:
          app-id: ${{vars.APP_ID}}
          private-key: ${{secrets.PRIVATE_KEY}}
          owner: ${{github.repository_owner}}
          repositories: "repo1,repo2"
      - uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9 # v1.6.1
        with:
          app-id: ${{vars.APP_ID}}
          private-key: ${{secrets.PRIVATE_KEY}}
