on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.PRIVATE_KEY}}
          repositories: >-
            ["${{github.event.repository.name}}"]
          permissions: >-
            {
              "contents": "read"
            }
