---
name: wc-test
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquaproj/aqua-installer@baef45299b36669c0015d0d8bc630272c3493e78 # v2.3.1
        with:
          aqua_version: v2.25.0
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: lintnet -v
      - run: lintnet lint
      - run: lintnet test
